//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceConsumerTest.AdvertisingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", ConfigurationName="AdvertisingService.PurchasingServiceSoap")]
    public interface PurchasingServiceSoap {
        
        // CODEGEN: Generating message contract since element name RequestOrderDetailsResult from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/RequestOrderDetails", ReplyAction="*")]
        ServiceConsumerTest.AdvertisingService.RequestOrderDetailsResponse RequestOrderDetails(ServiceConsumerTest.AdvertisingService.RequestOrderDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name CreateOrderDetailsResult from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/CreateOrderDetails", ReplyAction="*")]
        ServiceConsumerTest.AdvertisingService.CreateOrderDetailsResponse CreateOrderDetails(ServiceConsumerTest.AdvertisingService.CreateOrderDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/SendOrderDetails", ReplyAction="*")]
        void SendOrderDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/CreateInvoice", ReplyAction="*")]
        void CreateInvoice();
        
        // CODEGEN: Generating message contract since element name file from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/CreateDatabase", ReplyAction="*")]
        ServiceConsumerTest.AdvertisingService.CreateDatabaseResponse CreateDatabase(ServiceConsumerTest.AdvertisingService.CreateDatabaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOrderDetails", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ServiceConsumerTest.AdvertisingService.RequestOrderDetailsRequestBody Body;
        
        public RequestOrderDetailsRequest() {
        }
        
        public RequestOrderDetailsRequest(ServiceConsumerTest.AdvertisingService.RequestOrderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RequestOrderDetailsRequestBody {
        
        public RequestOrderDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOrderDetailsResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ServiceConsumerTest.AdvertisingService.RequestOrderDetailsResponseBody Body;
        
        public RequestOrderDetailsResponse() {
        }
        
        public RequestOrderDetailsResponse(ServiceConsumerTest.AdvertisingService.RequestOrderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class RequestOrderDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestOrderDetailsResult;
        
        public RequestOrderDetailsResponseBody() {
        }
        
        public RequestOrderDetailsResponseBody(string RequestOrderDetailsResult) {
            this.RequestOrderDetailsResult = RequestOrderDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrderDetails", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ServiceConsumerTest.AdvertisingService.CreateOrderDetailsRequestBody Body;
        
        public CreateOrderDetailsRequest() {
        }
        
        public CreateOrderDetailsRequest(ServiceConsumerTest.AdvertisingService.CreateOrderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateOrderDetailsRequestBody {
        
        public CreateOrderDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrderDetailsResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ServiceConsumerTest.AdvertisingService.CreateOrderDetailsResponseBody Body;
        
        public CreateOrderDetailsResponse() {
        }
        
        public CreateOrderDetailsResponse(ServiceConsumerTest.AdvertisingService.CreateOrderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class CreateOrderDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateOrderDetailsResult;
        
        public CreateOrderDetailsResponseBody() {
        }
        
        public CreateOrderDetailsResponseBody(string CreateOrderDetailsResult) {
            this.CreateOrderDetailsResult = CreateOrderDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDatabase", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ServiceConsumerTest.AdvertisingService.CreateDatabaseRequestBody Body;
        
        public CreateDatabaseRequest() {
        }
        
        public CreateDatabaseRequest(ServiceConsumerTest.AdvertisingService.CreateDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class CreateDatabaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string file;
        
        public CreateDatabaseRequestBody() {
        }
        
        public CreateDatabaseRequestBody(string file) {
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDatabaseResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ServiceConsumerTest.AdvertisingService.CreateDatabaseResponseBody Body;
        
        public CreateDatabaseResponse() {
        }
        
        public CreateDatabaseResponse(ServiceConsumerTest.AdvertisingService.CreateDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class CreateDatabaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateDatabaseResult;
        
        public CreateDatabaseResponseBody() {
        }
        
        public CreateDatabaseResponseBody(bool CreateDatabaseResult) {
            this.CreateDatabaseResult = CreateDatabaseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PurchasingServiceSoapChannel : ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchasingServiceSoapClient : System.ServiceModel.ClientBase<ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap>, ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap {
        
        public PurchasingServiceSoapClient() {
        }
        
        public PurchasingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchasingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchasingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchasingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceConsumerTest.AdvertisingService.RequestOrderDetailsResponse ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap.RequestOrderDetails(ServiceConsumerTest.AdvertisingService.RequestOrderDetailsRequest request) {
            return base.Channel.RequestOrderDetails(request);
        }
        
        public string RequestOrderDetails() {
            ServiceConsumerTest.AdvertisingService.RequestOrderDetailsRequest inValue = new ServiceConsumerTest.AdvertisingService.RequestOrderDetailsRequest();
            inValue.Body = new ServiceConsumerTest.AdvertisingService.RequestOrderDetailsRequestBody();
            ServiceConsumerTest.AdvertisingService.RequestOrderDetailsResponse retVal = ((ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap)(this)).RequestOrderDetails(inValue);
            return retVal.Body.RequestOrderDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceConsumerTest.AdvertisingService.CreateOrderDetailsResponse ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap.CreateOrderDetails(ServiceConsumerTest.AdvertisingService.CreateOrderDetailsRequest request) {
            return base.Channel.CreateOrderDetails(request);
        }
        
        public string CreateOrderDetails() {
            ServiceConsumerTest.AdvertisingService.CreateOrderDetailsRequest inValue = new ServiceConsumerTest.AdvertisingService.CreateOrderDetailsRequest();
            inValue.Body = new ServiceConsumerTest.AdvertisingService.CreateOrderDetailsRequestBody();
            ServiceConsumerTest.AdvertisingService.CreateOrderDetailsResponse retVal = ((ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap)(this)).CreateOrderDetails(inValue);
            return retVal.Body.CreateOrderDetailsResult;
        }
        
        public void SendOrderDetails() {
            base.Channel.SendOrderDetails();
        }
        
        public void CreateInvoice() {
            base.Channel.CreateInvoice();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceConsumerTest.AdvertisingService.CreateDatabaseResponse ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap.CreateDatabase(ServiceConsumerTest.AdvertisingService.CreateDatabaseRequest request) {
            return base.Channel.CreateDatabase(request);
        }
        
        public bool CreateDatabase(string file) {
            ServiceConsumerTest.AdvertisingService.CreateDatabaseRequest inValue = new ServiceConsumerTest.AdvertisingService.CreateDatabaseRequest();
            inValue.Body = new ServiceConsumerTest.AdvertisingService.CreateDatabaseRequestBody();
            inValue.Body.file = file;
            ServiceConsumerTest.AdvertisingService.CreateDatabaseResponse retVal = ((ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap)(this)).CreateDatabase(inValue);
            return retVal.Body.CreateDatabaseResult;
        }
    }
}
