//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceConsumerTest.AdvertisingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", ConfigurationName="AdvertisingService.PurchasingServiceSoap")]
    public interface PurchasingServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestOrderDetailsResult from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/requestOrderDetails", ReplyAction="*")]
        ServiceConsumerTest.AdvertisingService.requestOrderDetailsResponse requestOrderDetails(ServiceConsumerTest.AdvertisingService.requestOrderDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name createOrderDetailsResult from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/createOrderDetails", ReplyAction="*")]
        ServiceConsumerTest.AdvertisingService.createOrderDetailsResponse createOrderDetails(ServiceConsumerTest.AdvertisingService.createOrderDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/sendOrderDetails", ReplyAction="*")]
        void sendOrderDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/createInvoice", ReplyAction="*")]
        void createInvoice();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="requestOrderDetails", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ServiceConsumerTest.AdvertisingService.requestOrderDetailsRequestBody Body;
        
        public requestOrderDetailsRequest() {
        }
        
        public requestOrderDetailsRequest(ServiceConsumerTest.AdvertisingService.requestOrderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class requestOrderDetailsRequestBody {
        
        public requestOrderDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="requestOrderDetailsResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ServiceConsumerTest.AdvertisingService.requestOrderDetailsResponseBody Body;
        
        public requestOrderDetailsResponse() {
        }
        
        public requestOrderDetailsResponse(ServiceConsumerTest.AdvertisingService.requestOrderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class requestOrderDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestOrderDetailsResult;
        
        public requestOrderDetailsResponseBody() {
        }
        
        public requestOrderDetailsResponseBody(string requestOrderDetailsResult) {
            this.requestOrderDetailsResult = requestOrderDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createOrderDetails", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ServiceConsumerTest.AdvertisingService.createOrderDetailsRequestBody Body;
        
        public createOrderDetailsRequest() {
        }
        
        public createOrderDetailsRequest(ServiceConsumerTest.AdvertisingService.createOrderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class createOrderDetailsRequestBody {
        
        public createOrderDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createOrderDetailsResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ServiceConsumerTest.AdvertisingService.createOrderDetailsResponseBody Body;
        
        public createOrderDetailsResponse() {
        }
        
        public createOrderDetailsResponse(ServiceConsumerTest.AdvertisingService.createOrderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class createOrderDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string createOrderDetailsResult;
        
        public createOrderDetailsResponseBody() {
        }
        
        public createOrderDetailsResponseBody(string createOrderDetailsResult) {
            this.createOrderDetailsResult = createOrderDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PurchasingServiceSoapChannel : ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchasingServiceSoapClient : System.ServiceModel.ClientBase<ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap>, ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap {
        
        public PurchasingServiceSoapClient() {
        }
        
        public PurchasingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchasingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchasingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchasingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceConsumerTest.AdvertisingService.requestOrderDetailsResponse ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap.requestOrderDetails(ServiceConsumerTest.AdvertisingService.requestOrderDetailsRequest request) {
            return base.Channel.requestOrderDetails(request);
        }
        
        public string requestOrderDetails() {
            ServiceConsumerTest.AdvertisingService.requestOrderDetailsRequest inValue = new ServiceConsumerTest.AdvertisingService.requestOrderDetailsRequest();
            inValue.Body = new ServiceConsumerTest.AdvertisingService.requestOrderDetailsRequestBody();
            ServiceConsumerTest.AdvertisingService.requestOrderDetailsResponse retVal = ((ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap)(this)).requestOrderDetails(inValue);
            return retVal.Body.requestOrderDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceConsumerTest.AdvertisingService.createOrderDetailsResponse ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap.createOrderDetails(ServiceConsumerTest.AdvertisingService.createOrderDetailsRequest request) {
            return base.Channel.createOrderDetails(request);
        }
        
        public string createOrderDetails() {
            ServiceConsumerTest.AdvertisingService.createOrderDetailsRequest inValue = new ServiceConsumerTest.AdvertisingService.createOrderDetailsRequest();
            inValue.Body = new ServiceConsumerTest.AdvertisingService.createOrderDetailsRequestBody();
            ServiceConsumerTest.AdvertisingService.createOrderDetailsResponse retVal = ((ServiceConsumerTest.AdvertisingService.PurchasingServiceSoap)(this)).createOrderDetails(inValue);
            return retVal.Body.createOrderDetailsResult;
        }
        
        public void sendOrderDetails() {
            base.Channel.sendOrderDetails();
        }
        
        public void createInvoice() {
            base.Channel.createInvoice();
        }
    }
}
