//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientCompany.AdvertisingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInfo", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    [System.SerializableAttribute()]
    public partial class CustomerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        private double PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderInfo", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    [System.SerializableAttribute()]
    public partial class OrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderIDField;
        
        private ClientCompany.AdvertisingService.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderStatusField;
        
        private ClientCompany.AdvertisingService.CustomerInfo CustomerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public ClientCompany.AdvertisingService.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderStatusField, value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public ClientCompany.AdvertisingService.CustomerInfo Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", ConfigurationName="AdvertisingService.OrderManagerServiceSoap")]
    public interface OrderManagerServiceSoap {
        
        // CODEGEN: Generating message contract since element name info from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/InsertCustomer", ReplyAction="*")]
        ClientCompany.AdvertisingService.InsertCustomerResponse InsertCustomer(ClientCompany.AdvertisingService.InsertCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/FindCustomer", ReplyAction="*")]
        ClientCompany.AdvertisingService.FindCustomerResponse FindCustomer(ClientCompany.AdvertisingService.FindCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name GetCustomerByIdResult from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/GetCustomerById", ReplyAction="*")]
        ClientCompany.AdvertisingService.GetCustomerByIdResponse GetCustomerById(ClientCompany.AdvertisingService.GetCustomerByIdRequest request);
        
        // CODEGEN: Generating message contract since element name product from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/InsertProduct", ReplyAction="*")]
        ClientCompany.AdvertisingService.InsertProductResponse InsertProduct(ClientCompany.AdvertisingService.InsertProductRequest request);
        
        // CODEGEN: Generating message contract since element name productName from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/FindProduct", ReplyAction="*")]
        ClientCompany.AdvertisingService.FindProductResponse FindProduct(ClientCompany.AdvertisingService.FindProductRequest request);
        
        // CODEGEN: Generating message contract since element name RetrieveProductResult from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/RetrieveProduct", ReplyAction="*")]
        ClientCompany.AdvertisingService.RetrieveProductResponse RetrieveProduct(ClientCompany.AdvertisingService.RetrieveProductRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductByIdResult from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/GetProductById", ReplyAction="*")]
        ClientCompany.AdvertisingService.GetProductByIdResponse GetProductById(ClientCompany.AdvertisingService.GetProductByIdRequest request);
        
        // CODEGEN: Generating message contract since element name info from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/InsertOrder", ReplyAction="*")]
        ClientCompany.AdvertisingService.InsertOrderResponse InsertOrder(ClientCompany.AdvertisingService.InsertOrderRequest request);
        
        // CODEGEN: Generating message contract since element name RetrieveOrderResult from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/RetrieveOrder", ReplyAction="*")]
        ClientCompany.AdvertisingService.RetrieveOrderResponse RetrieveOrder(ClientCompany.AdvertisingService.RetrieveOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCustomer", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.InsertCustomerRequestBody Body;
        
        public InsertCustomerRequest() {
        }
        
        public InsertCustomerRequest(ClientCompany.AdvertisingService.InsertCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class InsertCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientCompany.AdvertisingService.CustomerInfo info;
        
        public InsertCustomerRequestBody() {
        }
        
        public InsertCustomerRequestBody(ClientCompany.AdvertisingService.CustomerInfo info) {
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCustomerResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.InsertCustomerResponseBody Body;
        
        public InsertCustomerResponse() {
        }
        
        public InsertCustomerResponse(ClientCompany.AdvertisingService.InsertCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertCustomerResponseBody {
        
        public InsertCustomerResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindCustomer", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.FindCustomerRequestBody Body;
        
        public FindCustomerRequest() {
        }
        
        public FindCustomerRequest(ClientCompany.AdvertisingService.FindCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class FindCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ClientCompany.AdvertisingService.CustomerInfo info;
        
        public FindCustomerRequestBody() {
        }
        
        public FindCustomerRequestBody(string email, ClientCompany.AdvertisingService.CustomerInfo info) {
            this.email = email;
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindCustomerResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.FindCustomerResponseBody Body;
        
        public FindCustomerResponse() {
        }
        
        public FindCustomerResponse(ClientCompany.AdvertisingService.FindCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class FindCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FindCustomerResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ClientCompany.AdvertisingService.CustomerInfo info;
        
        public FindCustomerResponseBody() {
        }
        
        public FindCustomerResponseBody(bool FindCustomerResult, ClientCompany.AdvertisingService.CustomerInfo info) {
            this.FindCustomerResult = FindCustomerResult;
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerById", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.GetCustomerByIdRequestBody Body;
        
        public GetCustomerByIdRequest() {
        }
        
        public GetCustomerByIdRequest(ClientCompany.AdvertisingService.GetCustomerByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class GetCustomerByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerID;
        
        public GetCustomerByIdRequestBody() {
        }
        
        public GetCustomerByIdRequestBody(int customerID) {
            this.customerID = customerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerByIdResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.GetCustomerByIdResponseBody Body;
        
        public GetCustomerByIdResponse() {
        }
        
        public GetCustomerByIdResponse(ClientCompany.AdvertisingService.GetCustomerByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class GetCustomerByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientCompany.AdvertisingService.CustomerInfo GetCustomerByIdResult;
        
        public GetCustomerByIdResponseBody() {
        }
        
        public GetCustomerByIdResponseBody(ClientCompany.AdvertisingService.CustomerInfo GetCustomerByIdResult) {
            this.GetCustomerByIdResult = GetCustomerByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertProduct", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.InsertProductRequestBody Body;
        
        public InsertProductRequest() {
        }
        
        public InsertProductRequest(ClientCompany.AdvertisingService.InsertProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class InsertProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientCompany.AdvertisingService.Product product;
        
        public InsertProductRequestBody() {
        }
        
        public InsertProductRequestBody(ClientCompany.AdvertisingService.Product product) {
            this.product = product;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertProductResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.InsertProductResponseBody Body;
        
        public InsertProductResponse() {
        }
        
        public InsertProductResponse(ClientCompany.AdvertisingService.InsertProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertProductResponseBody {
        
        public InsertProductResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindProduct", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.FindProductRequestBody Body;
        
        public FindProductRequest() {
        }
        
        public FindProductRequest(ClientCompany.AdvertisingService.FindProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class FindProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ClientCompany.AdvertisingService.Product product;
        
        public FindProductRequestBody() {
        }
        
        public FindProductRequestBody(string productName, ClientCompany.AdvertisingService.Product product) {
            this.productName = productName;
            this.product = product;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindProductResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.FindProductResponseBody Body;
        
        public FindProductResponse() {
        }
        
        public FindProductResponse(ClientCompany.AdvertisingService.FindProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class FindProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FindProductResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ClientCompany.AdvertisingService.Product product;
        
        public FindProductResponseBody() {
        }
        
        public FindProductResponseBody(bool FindProductResult, ClientCompany.AdvertisingService.Product product) {
            this.FindProductResult = FindProductResult;
            this.product = product;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveProduct", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.RetrieveProductRequestBody Body;
        
        public RetrieveProductRequest() {
        }
        
        public RetrieveProductRequest(ClientCompany.AdvertisingService.RetrieveProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetrieveProductRequestBody {
        
        public RetrieveProductRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveProductResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.RetrieveProductResponseBody Body;
        
        public RetrieveProductResponse() {
        }
        
        public RetrieveProductResponse(ClientCompany.AdvertisingService.RetrieveProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class RetrieveProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientCompany.AdvertisingService.Product[] RetrieveProductResult;
        
        public RetrieveProductResponseBody() {
        }
        
        public RetrieveProductResponseBody(ClientCompany.AdvertisingService.Product[] RetrieveProductResult) {
            this.RetrieveProductResult = RetrieveProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductById", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.GetProductByIdRequestBody Body;
        
        public GetProductByIdRequest() {
        }
        
        public GetProductByIdRequest(ClientCompany.AdvertisingService.GetProductByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class GetProductByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int productID;
        
        public GetProductByIdRequestBody() {
        }
        
        public GetProductByIdRequestBody(int productID) {
            this.productID = productID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductByIdResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.GetProductByIdResponseBody Body;
        
        public GetProductByIdResponse() {
        }
        
        public GetProductByIdResponse(ClientCompany.AdvertisingService.GetProductByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class GetProductByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientCompany.AdvertisingService.Product GetProductByIdResult;
        
        public GetProductByIdResponseBody() {
        }
        
        public GetProductByIdResponseBody(ClientCompany.AdvertisingService.Product GetProductByIdResult) {
            this.GetProductByIdResult = GetProductByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertOrder", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.InsertOrderRequestBody Body;
        
        public InsertOrderRequest() {
        }
        
        public InsertOrderRequest(ClientCompany.AdvertisingService.InsertOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class InsertOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientCompany.AdvertisingService.CustomerInfo info;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ClientCompany.AdvertisingService.Product product;
        
        public InsertOrderRequestBody() {
        }
        
        public InsertOrderRequestBody(ClientCompany.AdvertisingService.CustomerInfo info, ClientCompany.AdvertisingService.Product product) {
            this.info = info;
            this.product = product;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertOrderResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.InsertOrderResponseBody Body;
        
        public InsertOrderResponse() {
        }
        
        public InsertOrderResponse(ClientCompany.AdvertisingService.InsertOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertOrderResponseBody {
        
        public InsertOrderResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveOrder", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.RetrieveOrderRequestBody Body;
        
        public RetrieveOrderRequest() {
        }
        
        public RetrieveOrderRequest(ClientCompany.AdvertisingService.RetrieveOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetrieveOrderRequestBody {
        
        public RetrieveOrderRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveOrderResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.RetrieveOrderResponseBody Body;
        
        public RetrieveOrderResponse() {
        }
        
        public RetrieveOrderResponse(ClientCompany.AdvertisingService.RetrieveOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class RetrieveOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientCompany.AdvertisingService.OrderInfo[] RetrieveOrderResult;
        
        public RetrieveOrderResponseBody() {
        }
        
        public RetrieveOrderResponseBody(ClientCompany.AdvertisingService.OrderInfo[] RetrieveOrderResult) {
            this.RetrieveOrderResult = RetrieveOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderManagerServiceSoapChannel : ClientCompany.AdvertisingService.OrderManagerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderManagerServiceSoapClient : System.ServiceModel.ClientBase<ClientCompany.AdvertisingService.OrderManagerServiceSoap>, ClientCompany.AdvertisingService.OrderManagerServiceSoap {
        
        public OrderManagerServiceSoapClient() {
        }
        
        public OrderManagerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderManagerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderManagerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderManagerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientCompany.AdvertisingService.InsertCustomerResponse ClientCompany.AdvertisingService.OrderManagerServiceSoap.InsertCustomer(ClientCompany.AdvertisingService.InsertCustomerRequest request) {
            return base.Channel.InsertCustomer(request);
        }
        
        public void InsertCustomer(ClientCompany.AdvertisingService.CustomerInfo info) {
            ClientCompany.AdvertisingService.InsertCustomerRequest inValue = new ClientCompany.AdvertisingService.InsertCustomerRequest();
            inValue.Body = new ClientCompany.AdvertisingService.InsertCustomerRequestBody();
            inValue.Body.info = info;
            ClientCompany.AdvertisingService.InsertCustomerResponse retVal = ((ClientCompany.AdvertisingService.OrderManagerServiceSoap)(this)).InsertCustomer(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientCompany.AdvertisingService.FindCustomerResponse ClientCompany.AdvertisingService.OrderManagerServiceSoap.FindCustomer(ClientCompany.AdvertisingService.FindCustomerRequest request) {
            return base.Channel.FindCustomer(request);
        }
        
        public bool FindCustomer(string email, ref ClientCompany.AdvertisingService.CustomerInfo info) {
            ClientCompany.AdvertisingService.FindCustomerRequest inValue = new ClientCompany.AdvertisingService.FindCustomerRequest();
            inValue.Body = new ClientCompany.AdvertisingService.FindCustomerRequestBody();
            inValue.Body.email = email;
            inValue.Body.info = info;
            ClientCompany.AdvertisingService.FindCustomerResponse retVal = ((ClientCompany.AdvertisingService.OrderManagerServiceSoap)(this)).FindCustomer(inValue);
            info = retVal.Body.info;
            return retVal.Body.FindCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientCompany.AdvertisingService.GetCustomerByIdResponse ClientCompany.AdvertisingService.OrderManagerServiceSoap.GetCustomerById(ClientCompany.AdvertisingService.GetCustomerByIdRequest request) {
            return base.Channel.GetCustomerById(request);
        }
        
        public ClientCompany.AdvertisingService.CustomerInfo GetCustomerById(int customerID) {
            ClientCompany.AdvertisingService.GetCustomerByIdRequest inValue = new ClientCompany.AdvertisingService.GetCustomerByIdRequest();
            inValue.Body = new ClientCompany.AdvertisingService.GetCustomerByIdRequestBody();
            inValue.Body.customerID = customerID;
            ClientCompany.AdvertisingService.GetCustomerByIdResponse retVal = ((ClientCompany.AdvertisingService.OrderManagerServiceSoap)(this)).GetCustomerById(inValue);
            return retVal.Body.GetCustomerByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientCompany.AdvertisingService.InsertProductResponse ClientCompany.AdvertisingService.OrderManagerServiceSoap.InsertProduct(ClientCompany.AdvertisingService.InsertProductRequest request) {
            return base.Channel.InsertProduct(request);
        }
        
        public void InsertProduct(ClientCompany.AdvertisingService.Product product) {
            ClientCompany.AdvertisingService.InsertProductRequest inValue = new ClientCompany.AdvertisingService.InsertProductRequest();
            inValue.Body = new ClientCompany.AdvertisingService.InsertProductRequestBody();
            inValue.Body.product = product;
            ClientCompany.AdvertisingService.InsertProductResponse retVal = ((ClientCompany.AdvertisingService.OrderManagerServiceSoap)(this)).InsertProduct(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientCompany.AdvertisingService.FindProductResponse ClientCompany.AdvertisingService.OrderManagerServiceSoap.FindProduct(ClientCompany.AdvertisingService.FindProductRequest request) {
            return base.Channel.FindProduct(request);
        }
        
        public bool FindProduct(string productName, ref ClientCompany.AdvertisingService.Product product) {
            ClientCompany.AdvertisingService.FindProductRequest inValue = new ClientCompany.AdvertisingService.FindProductRequest();
            inValue.Body = new ClientCompany.AdvertisingService.FindProductRequestBody();
            inValue.Body.productName = productName;
            inValue.Body.product = product;
            ClientCompany.AdvertisingService.FindProductResponse retVal = ((ClientCompany.AdvertisingService.OrderManagerServiceSoap)(this)).FindProduct(inValue);
            product = retVal.Body.product;
            return retVal.Body.FindProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientCompany.AdvertisingService.RetrieveProductResponse ClientCompany.AdvertisingService.OrderManagerServiceSoap.RetrieveProduct(ClientCompany.AdvertisingService.RetrieveProductRequest request) {
            return base.Channel.RetrieveProduct(request);
        }
        
        public ClientCompany.AdvertisingService.Product[] RetrieveProduct() {
            ClientCompany.AdvertisingService.RetrieveProductRequest inValue = new ClientCompany.AdvertisingService.RetrieveProductRequest();
            inValue.Body = new ClientCompany.AdvertisingService.RetrieveProductRequestBody();
            ClientCompany.AdvertisingService.RetrieveProductResponse retVal = ((ClientCompany.AdvertisingService.OrderManagerServiceSoap)(this)).RetrieveProduct(inValue);
            return retVal.Body.RetrieveProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientCompany.AdvertisingService.GetProductByIdResponse ClientCompany.AdvertisingService.OrderManagerServiceSoap.GetProductById(ClientCompany.AdvertisingService.GetProductByIdRequest request) {
            return base.Channel.GetProductById(request);
        }
        
        public ClientCompany.AdvertisingService.Product GetProductById(int productID) {
            ClientCompany.AdvertisingService.GetProductByIdRequest inValue = new ClientCompany.AdvertisingService.GetProductByIdRequest();
            inValue.Body = new ClientCompany.AdvertisingService.GetProductByIdRequestBody();
            inValue.Body.productID = productID;
            ClientCompany.AdvertisingService.GetProductByIdResponse retVal = ((ClientCompany.AdvertisingService.OrderManagerServiceSoap)(this)).GetProductById(inValue);
            return retVal.Body.GetProductByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientCompany.AdvertisingService.InsertOrderResponse ClientCompany.AdvertisingService.OrderManagerServiceSoap.InsertOrder(ClientCompany.AdvertisingService.InsertOrderRequest request) {
            return base.Channel.InsertOrder(request);
        }
        
        public void InsertOrder(ClientCompany.AdvertisingService.CustomerInfo info, ClientCompany.AdvertisingService.Product product) {
            ClientCompany.AdvertisingService.InsertOrderRequest inValue = new ClientCompany.AdvertisingService.InsertOrderRequest();
            inValue.Body = new ClientCompany.AdvertisingService.InsertOrderRequestBody();
            inValue.Body.info = info;
            inValue.Body.product = product;
            ClientCompany.AdvertisingService.InsertOrderResponse retVal = ((ClientCompany.AdvertisingService.OrderManagerServiceSoap)(this)).InsertOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientCompany.AdvertisingService.RetrieveOrderResponse ClientCompany.AdvertisingService.OrderManagerServiceSoap.RetrieveOrder(ClientCompany.AdvertisingService.RetrieveOrderRequest request) {
            return base.Channel.RetrieveOrder(request);
        }
        
        public ClientCompany.AdvertisingService.OrderInfo[] RetrieveOrder() {
            ClientCompany.AdvertisingService.RetrieveOrderRequest inValue = new ClientCompany.AdvertisingService.RetrieveOrderRequest();
            inValue.Body = new ClientCompany.AdvertisingService.RetrieveOrderRequestBody();
            ClientCompany.AdvertisingService.RetrieveOrderResponse retVal = ((ClientCompany.AdvertisingService.OrderManagerServiceSoap)(this)).RetrieveOrder(inValue);
            return retVal.Body.RetrieveOrderResult;
        }
    }
}
