//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientCompany.AdvertisingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderInfo", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    [System.SerializableAttribute()]
    public partial class OrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderStatusField;
        
        private ClientCompany.AdvertisingService.CustomerInfo CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequirementField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderStatusField, value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public ClientCompany.AdvertisingService.CustomerInfo Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Requirement {
            get {
                return this.RequirementField;
            }
            set {
                if ((object.ReferenceEquals(this.RequirementField, value) != true)) {
                    this.RequirementField = value;
                    this.RaisePropertyChanged("Requirement");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInfo", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    [System.SerializableAttribute()]
    public partial class CustomerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", ConfigurationName="AdvertisingService.PurchasingServiceSoap")]
    public interface PurchasingServiceSoap {
        
        // CODEGEN: Generating message contract since element name RequestOrderDetailsResult from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/RequestOrderDetails", ReplyAction="*")]
        ClientCompany.AdvertisingService.RequestOrderDetailsResponse RequestOrderDetails(ClientCompany.AdvertisingService.RequestOrderDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name CreateOrderDetailsResult from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/CreateOrderDetails", ReplyAction="*")]
        ClientCompany.AdvertisingService.CreateOrderDetailsResponse CreateOrderDetails(ClientCompany.AdvertisingService.CreateOrderDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/SendOrderDetails", ReplyAction="*")]
        void SendOrderDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/CreateInvoice", ReplyAction="*")]
        void CreateInvoice();
        
        // CODEGEN: Generating message contract since element name info from namespace http://lab.cheonghyun.com:8888/AdvertisingService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lab.cheonghyun.com:8888/AdvertisingService/RequestOrder", ReplyAction="*")]
        ClientCompany.AdvertisingService.RequestOrderResponse RequestOrder(ClientCompany.AdvertisingService.RequestOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOrderDetails", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.RequestOrderDetailsRequestBody Body;
        
        public RequestOrderDetailsRequest() {
        }
        
        public RequestOrderDetailsRequest(ClientCompany.AdvertisingService.RequestOrderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RequestOrderDetailsRequestBody {
        
        public RequestOrderDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOrderDetailsResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.RequestOrderDetailsResponseBody Body;
        
        public RequestOrderDetailsResponse() {
        }
        
        public RequestOrderDetailsResponse(ClientCompany.AdvertisingService.RequestOrderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class RequestOrderDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestOrderDetailsResult;
        
        public RequestOrderDetailsResponseBody() {
        }
        
        public RequestOrderDetailsResponseBody(string RequestOrderDetailsResult) {
            this.RequestOrderDetailsResult = RequestOrderDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrderDetails", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.CreateOrderDetailsRequestBody Body;
        
        public CreateOrderDetailsRequest() {
        }
        
        public CreateOrderDetailsRequest(ClientCompany.AdvertisingService.CreateOrderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateOrderDetailsRequestBody {
        
        public CreateOrderDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrderDetailsResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.CreateOrderDetailsResponseBody Body;
        
        public CreateOrderDetailsResponse() {
        }
        
        public CreateOrderDetailsResponse(ClientCompany.AdvertisingService.CreateOrderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class CreateOrderDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateOrderDetailsResult;
        
        public CreateOrderDetailsResponseBody() {
        }
        
        public CreateOrderDetailsResponseBody(string CreateOrderDetailsResult) {
            this.CreateOrderDetailsResult = CreateOrderDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOrder", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.RequestOrderRequestBody Body;
        
        public RequestOrderRequest() {
        }
        
        public RequestOrderRequest(ClientCompany.AdvertisingService.RequestOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class RequestOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientCompany.AdvertisingService.OrderInfo info;
        
        public RequestOrderRequestBody() {
        }
        
        public RequestOrderRequestBody(ClientCompany.AdvertisingService.OrderInfo info) {
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOrderResponse", Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/", Order=0)]
        public ClientCompany.AdvertisingService.RequestOrderResponseBody Body;
        
        public RequestOrderResponse() {
        }
        
        public RequestOrderResponse(ClientCompany.AdvertisingService.RequestOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lab.cheonghyun.com:8888/AdvertisingService/")]
    public partial class RequestOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestOrderResult;
        
        public RequestOrderResponseBody() {
        }
        
        public RequestOrderResponseBody(string RequestOrderResult) {
            this.RequestOrderResult = RequestOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PurchasingServiceSoapChannel : ClientCompany.AdvertisingService.PurchasingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchasingServiceSoapClient : System.ServiceModel.ClientBase<ClientCompany.AdvertisingService.PurchasingServiceSoap>, ClientCompany.AdvertisingService.PurchasingServiceSoap {
        
        public PurchasingServiceSoapClient() {
        }
        
        public PurchasingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchasingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchasingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchasingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientCompany.AdvertisingService.RequestOrderDetailsResponse ClientCompany.AdvertisingService.PurchasingServiceSoap.RequestOrderDetails(ClientCompany.AdvertisingService.RequestOrderDetailsRequest request) {
            return base.Channel.RequestOrderDetails(request);
        }
        
        public string RequestOrderDetails() {
            ClientCompany.AdvertisingService.RequestOrderDetailsRequest inValue = new ClientCompany.AdvertisingService.RequestOrderDetailsRequest();
            inValue.Body = new ClientCompany.AdvertisingService.RequestOrderDetailsRequestBody();
            ClientCompany.AdvertisingService.RequestOrderDetailsResponse retVal = ((ClientCompany.AdvertisingService.PurchasingServiceSoap)(this)).RequestOrderDetails(inValue);
            return retVal.Body.RequestOrderDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientCompany.AdvertisingService.CreateOrderDetailsResponse ClientCompany.AdvertisingService.PurchasingServiceSoap.CreateOrderDetails(ClientCompany.AdvertisingService.CreateOrderDetailsRequest request) {
            return base.Channel.CreateOrderDetails(request);
        }
        
        public string CreateOrderDetails() {
            ClientCompany.AdvertisingService.CreateOrderDetailsRequest inValue = new ClientCompany.AdvertisingService.CreateOrderDetailsRequest();
            inValue.Body = new ClientCompany.AdvertisingService.CreateOrderDetailsRequestBody();
            ClientCompany.AdvertisingService.CreateOrderDetailsResponse retVal = ((ClientCompany.AdvertisingService.PurchasingServiceSoap)(this)).CreateOrderDetails(inValue);
            return retVal.Body.CreateOrderDetailsResult;
        }
        
        public void SendOrderDetails() {
            base.Channel.SendOrderDetails();
        }
        
        public void CreateInvoice() {
            base.Channel.CreateInvoice();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientCompany.AdvertisingService.RequestOrderResponse ClientCompany.AdvertisingService.PurchasingServiceSoap.RequestOrder(ClientCompany.AdvertisingService.RequestOrderRequest request) {
            return base.Channel.RequestOrder(request);
        }
        
        public string RequestOrder(ClientCompany.AdvertisingService.OrderInfo info) {
            ClientCompany.AdvertisingService.RequestOrderRequest inValue = new ClientCompany.AdvertisingService.RequestOrderRequest();
            inValue.Body = new ClientCompany.AdvertisingService.RequestOrderRequestBody();
            inValue.Body.info = info;
            ClientCompany.AdvertisingService.RequestOrderResponse retVal = ((ClientCompany.AdvertisingService.PurchasingServiceSoap)(this)).RequestOrder(inValue);
            return retVal.Body.RequestOrderResult;
        }
    }
}
